// AUTO-GENERATED by scripts/generate-manifest.js
// Do not edit by hand — re-run `bun run gen` after adding files to html_standalones/.
window.DEMO_MANIFEST = [
  { filename: "Abhay Standalone.html" },
  { filename: "Inventory Command Center.html" }
];
